// data.js
const products = [
  {
    id: 'p1',
    name: 'Organic Bananas',
    subtitle: '7pcs, Priceg',
    price: 4.99,
    image: require('./assets/placeholders/offer_banana.png'),
    section: 'shop',
    group: 'exclusive',
    category: 'Fresh Fruits',
    brand: 'Cocola',
    favorite: false,
    description: 'Fresh bananas placeholder.',
  },
  {
    id: 'p2',
    name: 'Naturel Red Apple',
    subtitle: '1kg, Priceg',
    price: 4.99,
    image: require('./assets/placeholders/offer_apple.png'),
    section: 'shop',
    group: 'exclusive',
    category: 'Fresh Fruits',
    brand: 'Ifad',
    favorite: false,
    description: 'Apples are nutritious.',
  },
  {
    id: 'p3',
    name: 'Bell Pepper Red',
    subtitle: '1kg, Priceg',
    price: 4.99,
    image: require('./assets/placeholders/best_selling_pepper.png'),
    section: 'shop',
    group: 'bestSelling',
    category: 'Vegetables',
    brand: 'Kazi Farms',
    favorite: false,
    description: 'Bell pepper placeholder.',
  },
  {
    id: 'p4',
    name: 'Fresh Ginger',
    subtitle: '250gm, Priceg',
    price: 2.99,
    image: require('./assets/placeholders/best_selling_ginger.png'),
    section: 'shop',
    group: 'bestSelling',
    category: 'Vegetables',
    brand: 'Individual Collection',
    favorite: false,
    description: 'Fresh ginger placeholder.',
  },
  {
    id: 'p5',
    name: 'Beef Bone',
    subtitle: '1kg, Priceg',
    price: 4.99,
    image: require('./assets/placeholders/grocery_beef.png'),
    section: 'shop',
    group: 'groceries',
    category: 'Meat',
    brand: 'Ifad',
    favorite: false,
    description: 'Beef bone placeholder.',
  },
  {
    id: 'p6',
    name: 'Broiler Chicken',
    subtitle: '1kg, Priceg',
    price: 4.99,
    image: require('./assets/placeholders/grocery_chicken.png'),
    section: 'shop',
    group: 'groceries',
    category: 'Meat',
    brand: 'Kazi Farms',
    favorite: false,
    description: 'Chicken placeholder.',
  },

  {
    id: 'b1',
    name: 'Diet Coke',
    subtitle: '355ml, Price',
    price: 1.99,
    image: require('./assets/placeholders/bev_diet_coke.png'),
    section: 'beverages',
    group: 'beverages',
    category: 'Beverages',
    brand: 'Cocola',
    favorite: true,
    description: 'Diet coke placeholder.',
  },
  {
    id: 'b2',
    name: 'Sprite Can',
    subtitle: '325ml, Price',
    price: 1.5,
    image: require('./assets/placeholders/bev_sprite.png'),
    section: 'beverages',
    group: 'beverages',
    category: 'Beverages',
    brand: 'Cocola',
    favorite: true,
    description: 'Sprite placeholder.',
  },
  {
    id: 'b3',
    name: 'Apple & Grape Juice',
    subtitle: '2L, Price',
    price: 15.5,
    image: require('./assets/placeholders/bev_apple_grape.png'),
    section: 'beverages',
    group: 'beverages',
    category: 'Beverages',
    brand: 'Ifad',
    favorite: true,
    description: 'Juice placeholder.',
  },
  {
    id: 'b4',
    name: 'Coca Cola Can',
    subtitle: '325ml, Price',
    price: 4.99,
    image: require('./assets/placeholders/bev_coca_cola.png'),
    section: 'beverages',
    group: 'beverages',
    category: 'Beverages',
    brand: 'Cocola',
    favorite: true,
    description: 'Coca cola placeholder.',
  },
  {
    id: 'b5',
    name: 'Pepsi Can',
    subtitle: '330ml, Price',
    price: 4.99,
    image: require('./assets/placeholders/bev_pepsi.png'),
    section: 'beverages',
    group: 'beverages',
    category: 'Beverages',
    brand: 'Individual Collection',
    favorite: true,
    description: 'Pepsi placeholder.',
  },

  {
    id: 's1',
    name: 'Egg Chicken Red',
    subtitle: '4pcs, Price',
    price: 1.99,
    image: require('./assets/placeholders/search_egg_red.png'),
    section: 'search',
    group: 'search',
    category: 'Eggs',
    brand: 'Cocola',
    favorite: false,
    description: 'Egg placeholder.',
  },
  {
    id: 's2',
    name: 'Egg Chicken White',
    subtitle: '180g, Price',
    price: 1.5,
    image: require('./assets/placeholders/search_egg_white.png'),
    section: 'search',
    group: 'search',
    category: 'Eggs',
    brand: 'Individual Collection',
    favorite: false,
    description: 'Egg placeholder.',
  },
  {
    id: 's3',
    name: 'Egg Pasta',
    subtitle: '30gm, Price',
    price: 15.99,
    image: require('./assets/placeholders/search_egg_pasta.png'),
    section: 'search',
    group: 'search',
    category: 'Noodles & Pasta',
    brand: 'Ifad',
    favorite: false,
    description: 'Pasta placeholder.',
  },
  {
    id: 's4',
    name: 'Egg Noodles',
    subtitle: '2L, Price',
    price: 15.99,
    image: require('./assets/placeholders/search_egg_noodles.png'),
    section: 'search',
    group: 'search',
    category: 'Noodles & Pasta',
    brand: 'Kazi Farms',
    favorite: false,
    description: 'Noodles placeholder.',
  },
  {
    id: 's5',
    name: 'Mayonnais Eggless',
    subtitle: '325ml, Price',
    price: 8.99,
    image: require('./assets/placeholders/search_mayo_eggless.png'),
    section: 'search',
    group: 'search',
    category: 'Chips & Crisps',
    brand: 'Cocola',
    favorite: false,
    description: 'Mayonnaise placeholder.',
  },
  {
    id: 's6',
    name: 'Egg Noodles Special',
    subtitle: '330ml, Price',
    price: 7.99,
    image: require('./assets/placeholders/search_egg_noodles2.png'),
    section: 'search',
    group: 'search',
    category: 'Fast Food',
    brand: 'Ifad',
    favorite: false,
    description: 'Noodles placeholder.',
  },
];

export default products;